### ISSUE TITLE
Doesn't update dependency

### ISSUE THREAD

**Issue by XF-FW** [mousabaker/poetry-plugin-up#41]
```
❯ poetry new abc
❯ cd abc
❯ poetry add "ruff@^0.1.1"
❯ rg ruff
pyproject.toml
10:ruff = "^0.1.1"

poetry.lock
4:name = "ruff"
10:    {file = "ruff-0.1.3-py3-none-macosx_10_7_x86_64.whl", hash = "sha256:b46d43d51f7061652eeadb426a9e3caa1e0002470229ab2fc19de8a7b0766901"},
etc...

❯ poetry up --latest
❯ # Nothing changes
❯ rg ruff
pyproject.toml
10:ruff = "^0.1.1"

poetry.lock
4:name = "ruff"
10:    {file = "ruff-0.1.3-py3-none-macosx_10_7_x86_64.whl", hash = "sha256:b46d43d51f7061652eeadb426a9e3caa1e0002470229ab2fc19de8a7b0766901"},

❯ poetry add ruff@latest
❯ # This did change the pyproject version
❯ rg ruff
pyproject.toml
10:ruff = "^0.1.3"

poetry.lock
4:name = "ruff"
10:    {file = "ruff-0.1.3-py3-none-macosx_10_7_x86_64.whl", hash = "sha256:b46d43d51f7061652eeadb426a9e3caa1e0002470229ab2fc19de8a7b0766901"},
```

Hopefully this helps in tracking the issue.

Just to clarify, am I right to say:

- After `poetry up --latest` the pyproject version should match the one in `poetry.lock`
- Doing `poetry up --latest` should be the same as running `poetry add package@latest` for every package.

Thanks

**Comment by Ravencentric** [comment]
Having the same issue on Windows 11 with Python 3.12 and Poetry 1.7.1

**Comment by jm-glowienke** [comment]
Any updates on this? For packages in the "0.x.x" range, I noticed the same behaviour, but that might be related to this PR: https://github.com/MousaZeidBaker/poetry-plugin-up/pull/26

**Comment by georgereynolds-metoffice** [comment]
I've had this occur e.g. in my `pyproject.toml` I have cfn-lint as `cfn-lint = "^0.83.3` but I couldn't get `poetry up` to grab the latest version at all - even using `--pinned --latest`. However, `poetry add <name>@latest --group dev' will update it to the correct version.

I think this is down to versions <1 see this line [link to code](https://github.com/MousaZeidBaker/poetry-plugin-up/blob/b7923309a9bfbc6ae15b933e74202480585183e1/src/poetry_plugin_up/command.py#L170)

**Comment by mustafa0x** [comment]
Yes, it doesn't update "0.x.x" deps. I replace "0.x.x" deps with '*' so that the plugin updates those deps.

**Comment by georgereynolds-metoffice** [comment]
I've updated the code to allow for this. I'll try and get a pull request

**Comment by y2kbugger** [comment]
Wow, I got really behind on some tooling because I didn't realize that updates were being skipped!

**Comment by mustafa0x** [comment]
solution: `perl -pi -e 's/\"\\^0.*?\"/\"*\"/g' pyproject.toml && poetry up --with=dev --latest --pinned`
