### ISSUE TITLE
(🎁) An option to exclude a list of dependencies

### ISSUE THREAD

**Issue by KotlinIsland** [mousabaker/poetry-plugin-up#9]
I would like to update all dependencies, except for a select few that I never want to update for various reasons.

Currently I would have to move these to a separate group:
```toml
[tool.poetry.group.dontupgrade.dependencies]
pendulum = "^1"
```
And execute `poetry up --without dontupgrade`.

This is not ideal as now the groups are no longer split into their semantic designations.

Another solution would be to specify exact versions as without `--pinned` these will be left alone. This still isn't optimal, because a user could desire updates within a range of these deps (bug fixes), but not major updates.

# Suggestion

`poetry up --exclude pendulum`

**Comment by m-roberts** [comment]
This would be great! I have exactly the same use-case.

**Comment by jaklan** [comment]
Also bumping the idea, that would be a really helpful feature
